import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { ArrowLeft, ArrowRight, Loader2, MessageSquare } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/components/ui/use-toast";

const CreateListing = () => {
  const [step, setStep] = useState(1);
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [idealPrice, setIdealPrice] = useState("");
  const [minPrice, setMinPrice] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);
  const { toast } = useToast();
  const navigate = useNavigate();

  // These would be generated by AI based on the title
  const followUpQuestions = [
    "What condition is it in?",
    "How long have you had it?",
    "Are there any special features worth mentioning?",
  ];

  const handleSubmit = async () => {
    if (!title.trim() || !description.trim() || !idealPrice || !minPrice) {
      toast({
        title: "Missing information",
        description: "Please fill in all the required fields",
        variant: "destructive",
      });
      return;
    }

    setIsProcessing(true);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        toast({
          title: "Authentication Error",
          description: "You must be logged in to create a listing",
          variant: "destructive",
        });
        return;
      }

      const { error } = await supabase
        .from('listings')
        .insert([
          {
            title: title,
            description: description,
            price: Number(idealPrice),
            image_url: 'https://via.placeholder.com/400',
            created_by: user.id,
            is_negotiable: Number(minPrice) < Number(idealPrice)
          }
        ]);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Your listing has been created!",
      });

      navigate('/my-items');
    } catch (error) {
      console.error('Error:', error);
      toast({
        title: "Error",
        description: "Failed to create listing. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const renderStep = () => {
    switch (step) {
      case 1:
        return (
          <div className="space-y-4">
            <h2 className="text-2xl font-semibold">What are you selling?</h2>
            <p className="text-muted-foreground">
              Give your item a clear, descriptive title
            </p>
            <Input
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g., iPhone 13 Pro Max 256GB"
              className="text-lg"
            />
            <Button 
              className="w-full"
              onClick={() => setStep(2)}
              disabled={!title.trim()}
            >
              Continue <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </div>
        );
      
      case 2:
        return (
          <div className="space-y-4">
            <h2 className="text-2xl font-semibold">Tell us more about your {title}</h2>
            <div className="space-y-4">
              {followUpQuestions.map((question, index) => (
                <div key={index} className="space-y-2">
                  <p className="font-medium">{question}</p>
                  <Textarea
                    className="min-h-[100px]"
                    placeholder="Type your answer here..."
                    onChange={(e) => setDescription(prev => 
                      `${prev}${prev ? '\n\n' : ''}${question}:\n${e.target.value}`
                    )}
                  />
                </div>
              ))}
            </div>
            <div className="flex gap-3">
              <Button variant="outline" onClick={() => setStep(1)}>
                <ArrowLeft className="mr-2 h-4 w-4" /> Back
              </Button>
              <Button 
                className="flex-1"
                onClick={() => setStep(3)}
                disabled={!description.trim()}
              >
                Continue <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </div>
          </div>
        );

      case 3:
        return (
          <div className="space-y-4">
            <h2 className="text-2xl font-semibold">Set your price</h2>
            <div className="space-y-4">
              <div className="space-y-2">
                <label className="text-sm font-medium">
                  What's your ideal price? (in €)
                </label>
                <Input
                  type="number"
                  value={idealPrice}
                  onChange={(e) => setIdealPrice(e.target.value)}
                  placeholder="e.g., 500"
                  className="text-lg"
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">
                  What's the minimum price you'd accept? (in €)
                </label>
                <Input
                  type="number"
                  value={minPrice}
                  onChange={(e) => setMinPrice(e.target.value)}
                  placeholder="e.g., 450"
                  className="text-lg"
                />
              </div>
            </div>
            <div className="flex gap-3">
              <Button variant="outline" onClick={() => setStep(2)}>
                <ArrowLeft className="mr-2 h-4 w-4" /> Back
              </Button>
              <Button 
                className="flex-1"
                onClick={handleSubmit}
                disabled={isProcessing || !idealPrice || !minPrice}
              >
                {isProcessing ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Processing...
                  </>
                ) : (
                  "Create Listing"
                )}
              </Button>
            </div>
          </div>
        );
    }
  };

  return (
    <div className="container max-w-2xl mx-auto px-4 py-8">
      <Button
        variant="ghost"
        onClick={() => navigate(-1)}
        className="mb-6"
      >
        <ArrowLeft className="mr-2 h-4 w-4" /> Back
      </Button>

      <div className="bg-card rounded-lg shadow-lg p-6">
        {renderStep()}
      </div>
    </div>
  );
};

export default CreateListing;