// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gafcairgbtzdkmysddjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhZmNhaXJnYnR6ZGtteXNkZGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNjY4MzYsImV4cCI6MjA1MTg0MjgzNn0.Js-l1H0xNoBOy3UaTZAEbd47ai0r5kpR_VhSyJc9rTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);